### ISSUE TITLE
Inconsistent serialization with --output-format=json vs yaml

### ISSUE THREAD

**Issue by jethron** [snowplow/snowplow-cli#84]
When using `generate --output-format=json` for some commands, the output serializes to objects with different casing.

e.g.
- `$.data.Name` vs `$.data.name`
- `$.data.Entities` vs `$.data.entities`

Also in some cases, yaml generates empty arrays whereas JSON generates null values.

```console
snowplow-cli dp generate --source-app my-source-app
snowplow-cli dp generate --source-app my-source-app --output-format json
```

```yaml
apiVersion: v1
resourceType: source-application
resourceName: 17a7eb07-4c14-4e23-ad1f-26624ac1b938
data:
    name: my-source-app
    appIds: []
    entities:
        tracked: []
        enriched: []
```

```json
{
  "apiVersion": "v1",
  "resourceType": "source-application",
  "resourceName": "dd2f61cc-3f9b-4de0-a39c-b9513ff57616",
  "data": {
    "Name": "my-source-app",
    "appIds": [],
    "Entities": {
      "Tracked": null,
      "Enriched": null
    }
  }
}
```

These probably work ok for the CLI since the golang JSON marshaller falls back to case-insensitive field names, but other languages do not; this means custom tooling that works with the files potentially has to handle both cases.

Ideally both formats would deserialize identically in general cases.
