### ISSUE TITLE
Data product validation error: Something went wrong

### ISSUE THREAD

**Issue by jongracecox** [snowplow/snowplow-cli#88]
I am using the `snowplow-cli` to perform data product validation for a very set of large data product YAML files. I am running the CLI as follows:

```bash
snowplow-cli data-products --debug validate
```

During execution I get the following error messages:

```text
56PM ERRO validating file=data-products/redacted.yaml unexpected error checking compatibility got: bad response got status: 500 with message: Something went wrong
3:56PM ERRO validating file=data-products/redacted.yaml unexpected error checking compatibility got: bad response got status: 500 with message: Something went wrong
```

Running with `--json-output` option does not reveal any additional information:

```json
{"time":"2025-04-18T16:42:24.804692-04:00","level":"ERROR","msg":"validating","file":"data-products/redacted.yaml","msg":"unexpected error checking compatibility got: bad response got status: 500 with message: Something went wrong"}
```

I tested with both version `0.0.8` and `0.0.9`.

I am not able to share my data product file as part of this issue, but am in contact with my companies Snowplow account team. The data product file is 43k lines long(!), so it is difficult to narrow down on the issue.

During my investigation I wanted to know the order that event specifications are validated. When I look at the command output I can see the preceding event specifications (based on array position), but the order is not predictable. I was hoping to be able to figure out the order so that I could determine which event specification is at fault. In my case the the preceding event specs are:

```text
path=/data/eventSpecifications/30
path=/data/eventSpecifications/32
path=/data/eventSpecifications/139
path=/data/eventSpecifications/154
path=/data/eventSpecifications/234
path=/data/eventSpecifications/14
```

I also updated my VSCode settings to use the [data-product JSON schema](https://github.com/snowplow/snowplow-cli/blob/main/internal/validation/schema/data-product.json) from this project to ensure there are no issues.
I did this by creating a `schemas/` directory in the root of my project, downloading the JSON schema, and adding the following to my settings:

```json
    "yaml.schemas": {
      "./schemas/data-product.json": "data-products/*.yaml"
    }
```

**Comment by jongracecox** [comment]
I updated the go code to display the path of the offending item, and was able to use this to identify the offending two event specifications. I created PR #89 with the changes I made, and hope these can be added to the tool.

When I inspected the two failing event specifications I spotted some malformed `enum` values:

```
                                    enum:
                                        - 'text <text>: text

                                            text <text>: text'
```

I haven't tested, but I assume it's the new lines that are causing the internal server error.

Suggested follow-up actions would be to extend the JSON schema to prevent new line characters in enum value (if this is the cause) and review server-side code.

The full, but heavily redacted, data product file is included below:

```yaml
data:
    eventSpecifications:
        -   resourceName: REDACTED
            name: REDACTED
            description: REDACTED
            event:
                source: iglu:com.REDACTED
                schema:
                    $schema: http://json-schema.org/draft-04/schema#
                    additionalProperties: false
                    properties:
                        REDACTED:
                            type: boolean
                            description: ''
                        REDACTED:
                            type: boolean
                            description: ''
                    required:
                        - REDACTED
                        - REDACTED
                    type: object
            entities:
                tracked:
                    -   source: REDACTED
                        minCardinality: 1
                        maxCardinality: 1
                        schema:
                            $schema: http://json-schema.org/draft-04/schema#
                            additionalProperties: false
                            properties:
                                propname:
                                    type: string
                                    description: prop description
                                    enum:
                                        - 'text <text>: text

                                            text <text>: text'
                            required:
                                - propname
                            type: object
                enriched: []
            triggers: []
```
